#!/bin/bash
STATUS=`/opt/MegaRAID/MegaCli/MegaCli64 -AdpAllInfo -aALL -NoLog | grep "Degraded\|Failed Disks\|Critical" | grep -v ' 0'`

if [ "x$STATUS" != "x" ]; then
  echo "The condition of your RAID array on servebot has degraded. Begin recovery as soon as possible." | mail -s "RAID Alert" $EMAIL_ADDR
fi
